// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_YCIS505YlGDRILak2Z6eMrtsIF1xNao',
    appId: '1:75063445743:web:3fef1217e17fecd69df31a',
    messagingSenderId: '75063445743',
    projectId: 'pos-app-fc051',
    authDomain: 'pos-app-fc051.firebaseapp.com',
    storageBucket: 'pos-app-fc051.firebasestorage.app',
    measurementId: 'G-NBV3W03460',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnmAeqmczE4vCycXhEokA8zxQDJEveQtQ',
    appId: '1:75063445743:android:12de5b504d3df2a59df31a',
    messagingSenderId: '75063445743',
    projectId: 'pos-app-fc051',
    storageBucket: 'pos-app-fc051.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnVDJ0y1TMea-68Xd_r3_xgAcVUBJKW_A',
    appId: '1:75063445743:ios:0bdf68de55b104e09df31a',
    messagingSenderId: '75063445743',
    projectId: 'pos-app-fc051',
    storageBucket: 'pos-app-fc051.firebasestorage.app',
    iosBundleId: 'com.example.test1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnVDJ0y1TMea-68Xd_r3_xgAcVUBJKW_A',
    appId: '1:75063445743:ios:0bdf68de55b104e09df31a',
    messagingSenderId: '75063445743',
    projectId: 'pos-app-fc051',
    storageBucket: 'pos-app-fc051.firebasestorage.app',
    iosBundleId: 'com.example.test1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_YCIS505YlGDRILak2Z6eMrtsIF1xNao',
    appId: '1:75063445743:web:617a417b036b260a9df31a',
    messagingSenderId: '75063445743',
    projectId: 'pos-app-fc051',
    authDomain: 'pos-app-fc051.firebaseapp.com',
    storageBucket: 'pos-app-fc051.firebasestorage.app',
    measurementId: 'G-RJ75Z7VR43',
  );
}
